// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFKLJz_iDBJ3nlRW8XWfvBarVidSPrds',
    appId: '1:1003388316244:web:3c50fcd9419e23e1c01bc1',
    messagingSenderId: '1003388316244',
    projectId: 'municipality-corp',
    authDomain: 'municipality-corp.firebaseapp.com',
    databaseURL: 'https://municipality-corp-default-rtdb.firebaseio.com',
    storageBucket: 'municipality-corp.appspot.com',
    measurementId: 'G-RSEYSVLC93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4PpuWN2pA9kqWKvWtoGAFbEONZ8UZYA',
    appId: '1:58548553120:android:d991180c2f2dbd74fb50c5',
    messagingSenderId: '58548553120',
    projectId: 'studentfoodservice-82f3b',
    databaseURL: 'https://studentfoodservice-82f3b-default-rtdb.firebaseio.com',
    storageBucket: 'studentfoodservice-82f3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYNQSbnsdx-KPTUvGSchf2HHbHzunsO4E',
    appId: '1:1003388316244:ios:d51e0a0b33d4a06dc01bc1',
    messagingSenderId: '1003388316244',
    projectId: 'municipality-corp',
    databaseURL: 'https://municipality-corp-default-rtdb.firebaseio.com',
    storageBucket: 'municipality-corp.appspot.com',
    iosBundleId: 'com.example.tourist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYNQSbnsdx-KPTUvGSchf2HHbHzunsO4E',
    appId: '1:1003388316244:ios:d51e0a0b33d4a06dc01bc1',
    messagingSenderId: '1003388316244',
    projectId: 'municipality-corp',
    databaseURL: 'https://municipality-corp-default-rtdb.firebaseio.com',
    storageBucket: 'municipality-corp.appspot.com',
    iosBundleId: 'com.example.tourist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKFKLJz_iDBJ3nlRW8XWfvBarVidSPrds',
    appId: '1:1003388316244:web:9ff97a4a8b9ec796c01bc1',
    messagingSenderId: '1003388316244',
    projectId: 'municipality-corp',
    authDomain: 'municipality-corp.firebaseapp.com',
    databaseURL: 'https://municipality-corp-default-rtdb.firebaseio.com',
    storageBucket: 'municipality-corp.appspot.com',
    measurementId: 'G-YYCS8X4QCM',
  );

}